int iniciar_ADC(void);
int iniciar_interrupciones(void);
int iniciar_FLASH(void);
int iniciar_UART(void);
void iniciar_timer0(void);
void iniciar_timer2(void);
// void iniciar_PCA(void);
void iniciar_puertos (void);
void iniciar_sysclock (void);
void iniciar_osc_externo(void);
void seleccionar_puerto(unsigned short *puerto);
void empezar_adc();
