void iniciar_puertos (void);
void iniciar_sysclock (void);
int iniciar_ADC(void);
void iniciar_UART(void);
void iniciar_timer0(void);
void iniciar_timer2(void);
void iniciar_contadorRPM(void);
void iniciar_osc_externo(void);
void iniciar_PCA (void);
void habilitar_modo_bajo_consumo(void);
void deshabilitar_modo_bajo_consumo(void);